version: '3'

services:
  php:
    build:
      context: ./php7.2
    container_name: lamp-php
    volumes:
      - ./php7.2/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
      - ./log/xdebug.log:/tmp/xdebug.log
    ports:
      - 80:80
    tty: true
    stdin_open: true
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: lamp-mysql
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions